### ISSUE TITLE
Support pandoc v2 and --lua-filter

### ISSUE THREAD

**Issue by mdourmousoglou** [NicklasTegner/pypandoc#155]
Currently all filters passed to `convert_input` are explicitly assumed to be JSON filters ([line 280](https://github.com/bebraw/pypandoc/blob/6d5a0a667c93220e6837db71525e738eade525c5/pypandoc/__init__.py#L280)). Pandoc v2 accepts Lua filters with a new `--lua-filter` option but it won't accept a Lua filter passed just with `--filter` (or the other way around).

**Comment by slackline** [comment]
Is there scope for getting `pypandoc` to play ball with [`pandocfilters`](https://pypi.org/project/pandocfilters/)?  I know its not a Lua filter but if you're working with `pypandoc` in Python anyway.

**Comment by jankatins** [comment]
Feel free to write PR for this. As I don't use filters, I cannot really play with this :-/
