### ISSUE TITLE
pypandoc-1.4 FreeBSD package fails in build: Pandoc died with exitcode "97" during conversion: b'Could not find data file

### ISSUE THREAD

**Issue by yurivict** [NicklasTegner/pypandoc#179]
See the log: http://beefy6.nyi.freebsd.org/data/120amd64-default/501212/logs/py36-pypandoc-1.4.log

This started happening after the update of some other package, I think.

**Comment by jankatins** [comment]
Does pandoc itself work? This looks more like a packaging bug in pandoc so it might nowadays be fixed?
