### ISSUE TITLE
`pdf-engine wkhtmltopdf is not compatible with output format pdf`

### ISSUE THREAD

**Issue by NatalieThurlby** [NicklasTegner/pypandoc#186]
I'm having the following problem:

I'm running:
```
            pypandoc.convert_file(
            html_file,
            'pdf',
            outputfile=pdf_file,
            extra_args=['--pdf-engine', 'wkhtmltopdf','--to','pdf'],
        )
```
And I get the error `pdf-engine wkhtmltopdf is not compatible with output format pdf`, even though wkhtml2pdf should be able to output to pdf and when I run pandoc in the terminal on the same file (`pandoc path/to/html_file.html -o pdf_file.pdf --pdf-engine wkhtmltopdf`), it works fine. 

If I don't have the `'--to', 'pdf'` options in pypandoc, I get the following error message instead:
`pdf-engine wkhtmltopdf is not compatible with output format latex`

Any ideas as to why this might be happening?

**Comment by jankatins** [comment]
No clue, this is the first time i hear abotu this engine :-(

You could edit __init__.py and add a `print(args)` in line 285 (before the line `p = subprocess.Popen(`) and then check what we do differently...

**Comment by snan** [comment]
Hi Natalie, I had the same problem today but I figured it out: use `--to html` instead of `--to pdf` and then make sure your outputfile ends with the `.pdf` extension.

**Comment by NicklasTegner** [comment]
@snan solution seems to work, if there's need for us to modify the behavior, feel free to open an issue or submit a pr-
