### ISSUE TITLE
RuntimeError: Pandoc died with exitcode "63" during conversion: b"couldn't parse docx file\n"

### ISSUE THREAD

**Issue by Durgesh-Chalvadi** [NicklasTegner/pypandoc#190]
RuntimeError: Pandoc died with exitcode "63" during conversion: b"couldn't parse docx file\n"

**Comment by Amazing-DataScience** [comment]
While converting docx file into html encountered this error

**Comment by jankatins** [comment]
Sorry, this is a pandoc error, could you try running the conversion directly with pandoc and report the error to pandoc?

**Comment by bhpayne** [comment]
> RuntimeError: Pandoc died with exitcode "63" during conversion: b"couldn't parse docx file\n"

Hello @Durgesh-Chalvadi -- I also encountered the problem you describe. To verify that the issue wasn't with the input, I verified the conversion process [using a web interface](https://pandoc.org/try/?text=%3D%3DLife%3D%3D%0AHe+was+born+in+London+on+19+July+1800%2C+a+son+of+%5B%5BJames+Millingen%5D%5D.+He+spent+his+early+years+in+%5B%5BCalais%5D%5D+and+%5B%5BParis%5D%5D%2C+and+was+sent+to+school+in+%5B%5BRome%5D%5D.+In+holidays+he+took+walking+tours+in+Germany%2C+on+one+of+which+he+is+said+to+have+visited+%5B%5BGoethe%5D%5D+in+%5B%5BWeimar%5D%5D.+In+1817+he+entered+the+%5B%5BUniversity+of+Edinburgh%5D%5D%2C+and+attended+medical+classes+there+until+1821%2C+when+he+received+a+diploma+from+the+%5B%5BRoyal+College+of+Surgeons+of+Edinburgh%5D%5D.%3Cref+name%3D%22DNB%22%3E%7B%7Bcite+DNB%7Cwstitle%3DMillingen%2C+Julius+Michael%7Cvolume%3D37%7D%7D%3C%2Fref%3E%0A%0AWhen+the+%5B%5BLondon+Philhellenic+Committee%5D%5D+was+formed%2C+Millingen+was+recommended+to+it+by+%5B%5BWilliam+Smith+(abolitionist)%7CWilliam+Smith%5D%5D%2C+and+on+27+August+1823+he+left+England+for+%5B%5BCorfu%5D%5D%2C+with+letters+of+introductio&from=mediawiki&to=latex&standalone=0)

Then I read on [https://pypi.org/project/pypandoc/](https://pypi.org/project/pypandoc/) that "It's also possible to directly let pandoc write the output to a file. This is the only way to convert to some output formats (e.g. odt, docx, epub, epub3, pdf)". 

Are you writing the output to a .docx file?

**Comment by NicklasTegner** [comment]
as @bhpayne pointed out, this is the only way to write some output formats.

As the original author hasn't responded, I see this issue as resolved.
If not, feel free to open a new issue!
