### ISSUE TITLE
Wheel dependency

### ISSUE THREAD

**Issue by AbdealiJK** [NicklasTegner/pypandoc#198]
I was trying to use this library - but found that 'wheel' is a install dependency ?
Wasn't sure if that was valid or needed ? Shouldn't it be a setup-dependency ?

**Comment by NicklasTegner** [comment]
Hi there
I'll look into it, once I get the code a little cleaned up :)

**Comment by AbdealiJK** [comment]
@NicklasTegner Let me know if I can create a PR for this and any specific testing you may want me to do here
I'm happy to contribute

**Comment by AbdealiJK** [comment]
Just a FYI - I now see that the package on pypi does not need `wheel` (I assume that was created using the poetry stuff)
But the setup.py still says it required `wheel` - which is causing confusion in my build pipelines because I am testing with both the plain python version and also the one with the `download_pandoc` version.

Have also raised https://github.com/NicklasTegner/pypandoc/issues/279
