### ISSUE TITLE
"openBinaryFile: does not exist" error when attempting to use template with extra_args

### ISSUE THREAD

**Issue by c-forster** [NicklasTegner/pypandoc#203]
When I try to pass a template to `convert_text` I get the following error:

```
Traceback (most recent call last):
  File "templatetest.py", line 5, in <module>
    print(pypandoc.convert_text(text, 'html', format='md',extra_args=["template testTemplate.html"]))
  File "~/venv/lib/python3.7/site-packages/pypandoc/__init__.py", line 101, in convert_text
    outputfile=outputfile, filters=filters)
  File "~/venv/lib/python3.7/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: template testTemplate.html: openBinaryFile: does not exist (No such file or directory)\n'
```

I can use the template without error if I call pandoc directly from the command line. I have tried using an absolute path, but without luck.

Using Python 3.7.4 in a virtual environment, with pypandoc 2.11.0.2.

```
> python
Python 3.7.4 (default, Oct  4 2019, 13:46:40)
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypandoc
>>> print(pypandoc.get_pandoc_version())
2.11.0.2
>>> print(pypandoc.get_pandoc_path())
pandoc
```

**Comment by doersino** [comment]
You need to split the extra arguments into a list of strings, i.e. `['--template', 'template.latex']`

As the readme notes (in a different context, but it also applies for your use case):

> This gotcha has to do with the way [`subprocess.Popen`](https://docs.python.org/2/library/subprocess.html#subprocess.Popen) works.

Notice that you've also omitted the two dashes, `--`, which is another reason your invocation didn't work.

**Comment by NicklasTegner** [comment]
As the original author hasn't responded, I see this issue as resolved.
If not, feel free to open a new issue!
