### ISSUE TITLE
Install Pandoc inside Azure Function for Pypandoc

### ISSUE THREAD

**Issue by arpalani** [NicklasTegner/pypandoc#207]
I am using the package [pypandoc](https://pypi.org/project/pypandoc/) for converting DOC/DOCX files into HTML. This has a prerequisite of Pandoc being already installed. When both packages are installed using the `requirements.txt` file, it works locally. When I deploy it as an Azure Function, however, it always gives a "module not found" error. (pypandoc cannot find pandoc in the same path because it gets installed elsewhere.)

This seems like a known issue. Pandoc does not get installed in the same path as Pyandoc and there are multiple solutions suggested. But they only locally.

**Options tried:**

1. [Use `pandoc_download`](https://pypi.org/project/pypandoc/)

   ```python
   from pypandoc.pandoc_download import download_pandoc
   ```

2. [Use wdc](https://github.com/watson-developer-cloud/python-sdk/issues/324). This does not fix the problem.

3. [Use wheel files](https://github.com/bebraw/pypandoc/issues/173) that include Pandoc.

Right now I am using mammoth for conversion which is slightly lower in accuracy, but gets deployed on Az. How can I get Pypandoc working as an Azure Function? How can I install Pandoc in a place where Pypandoc can find it? Or, how can I tell Pypandoc where to find Pandoc?

**Comment by NicklasTegner** [comment]
Hi there

If you know the installation path of pandoc, you can hard code it in with the following

``
os.environ.setdefault('PYPANDOC_PANDOC', "C:/full/path/to/pandoc/folder/")

`

**Comment by NicklasTegner** [comment]
Hi. Since I haven't heard anything, I'll mark this issue as closed.
If you still need help, or have found a bug, feel free to reopen or make a new issue :)
