### ISSUE TITLE
Important - Call for new maintainers

### ISSUE THREAD

**Issue by bebraw** [NicklasTegner/pypandoc#208]
Given I and Jan have moved on and we don't use pypandoc anymore but the package itself is still popular, we're looking new maintainers for it to merge the open PRs and keep an eye on the issues.

If you have interest in taking over the package, please ping me in this thread. We're happy to move the repository and provide necessary access for the CI and publishing process.

**Comment by NicklasTegner** [comment]
Hi everyone.

From today, I have gotten the honor to continue PyPandoc

Thanks so much to @bebraw  and Jan for their work on this!

I'll be taking a look at all the issues and prs in the next couple of days.

Looking forward to working with you all! :)

**Comment by bebraw** [comment]
Great. Thanks for taking over. It's time to close this issue. 👍
