### ISSUE TITLE
Executable not found for --citeproc while parsing the LaTeX to docx using pypandoc

### ISSUE THREAD

**Issue by vissa1604** [NicklasTegner/pypandoc#209]
Hi folks, 
I am trying to parse a LaTeX file to docx using pypandoc(a python third party package) and I got an exception stating "--citeproc: could not find executable" 

It would be really great if someone can help me with a solution for this

Thanks in advance

**Comment by NicklasTegner** [comment]
Hi there
The error should be resolved in the next release of PyPandoc, since citeproc isn't an executable anymore)
