### ISSUE TITLE
pypandoc-citeproc has been deprecated

### ISSUE THREAD

**Issue by sternenseemann** [NicklasTegner/pypandoc#211]
`pypandoc-citeproc` has been deprecated by upstream in favor of the `pandoc --citeproc` option. We should switch to that for the test suite and the `filters` argument will probably also need to be redone or at least its documentation changed.

**Comment by gliptak** [comment]
Builds seem to be failing not finding `pandoc-citeproc` https://travis-ci.org/github/bebraw/pypandoc/jobs/768316665#L432

**Comment by NicklasTegner** [comment]
Hi there.

This issue should be fixed now, and will be in the next release of PyPandoc [(version 1.6)](https://github.com/NicklasTegner/pypandoc/milestone/1)
