### ISSUE TITLE
can't use or load pandoc from .app generate by py2App on MacOs

### ISSUE THREAD

**Issue by PhilippeDou** [NicklasTegner/pypandoc#212]
Dear,
When I use **pypandoc.get_pandoc_version()** function on MacOs Catalina, if I execute this code from .app generated by Py2App, I have an issue : 
_<class 'OSError'> : No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc._

I have add **pypandoc.download_pandoc()** before but I have this issue : 
_<class 'urllib.error.URLError'> : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>_

But if I launch my application from with **python3 myApp.py** I have no issue and pypandoc works correctly.

If I launch my Python application from Contents->MacOs->MyApp of App, pypandoc works correctly too.

Could you help me ?

Best regards
Philippe

**Comment by NicklasTegner** [comment]
Hi.

This looks to be out of the scope of PyPandoc, you might find this link useful: https://www.dev2qa.com/how-to-fix-python-error-certificate-verify-failed-unable-to-get-local-issuer-certificate-in-mac-os/

Other than that, I would suggest googling the error.
