### ISSUE TITLE
pandoc-*-arm64.deb breaks Debian auto download

### ISSUE THREAD

**Issue by gliptak** [NicklasTegner/pypandoc#216]
https://github.com/jgm/pandoc/releases/tag/2.13

https://travis-ci.org/github/bebraw/pypandoc/jobs/768518864#L425

```
$ ~/bin/pandoc -v

/home/travis/.travis/functions: line 109: /home/travis/bin/pandoc: cannot execute binary file: Exec format error
```

**Comment by NicklasTegner** [comment]
Hi there

this issue has been fixed, and will be out in [the next version, 1.6](https://github.com/NicklasTegner/pypandoc/milestone/1)
