### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by joetheone** [NicklasTegner/pypandoc#224]
Hello @NicklasTegner ,

Will you be making a release for version 1.6.3? I would love to see release notes somewhere before I update.

Thanks!

**Comment by NicklasTegner** [comment]
hi @joetheone 

Thanks for catching that.
I've now written some changelog entries, which you can find on the release [here](https://github.com/NicklasTegner/pypandoc/releases/tag/1.6.3)

I hope this was, what you had in mind.
Thanks for the issue :)

**Comment by joetheone** [comment]
great thanks!
