### ISSUE TITLE
image path - when converting from org mode to markdown

### ISSUE THREAD

**Issue by yashasolutions** [NicklasTegner/pypandoc#228]
Hi,

When converting orgmode from markdow, image path is converted into a local path for some reason.

Example 

```org
[[/uploads/760d47f629c516535b2f5e98ef359343/Group_33.png]]
```

is becoming 
```markdown
![](file:///uploads/760d47f629c516535b2f5e98ef359343/Group_33.png)
```

instead of :
```
![](/uploads/760d47f629c516535b2f5e98ef359343/Group_33.png)
```

Any idea how to avoid this?

**Comment by NicklasTegner** [comment]
Hi
The only option I can think of, is to set the "--extract-media=path" option.
Do let me know if that works.
