### ISSUE TITLE
Report'[WinError 5]'

### ISSUE THREAD

**Issue by lp20010415** [NicklasTegner/pypandoc#229]
前天还是好好的，结果今天一用就这样了，不知道是不是因为cmder的原因QWQ。但是我把cmder卸载了，可能卸载的不彻底。希望能告知一个解决方法，感恩！
Translate:
It was good the day before yesterday. As a result, it's like this as soon as it's used today. I don't know if it's because of the cmder, qwq. But I uninstalled the cmder, which may not be completely uninstalled. I hope you can tell me a solution. Thank you!

Here is the error code:
![image](https://user-images.githubusercontent.com/56969920/129518171-1ae69943-a664-40f7-8eff-467ef6df6a10.png)

**Comment by lp20010415** [comment]
![image](https://user-images.githubusercontent.com/56969920/129518606-265c7f9f-2e88-493b-90d2-f389f0f2c05a.png)

**Comment by NicklasTegner** [comment]
It looks like it finds pandoc, but for some reason it can't use it because of an error.
I would suggest checking if the pandoc found is indeed set as being executable, as this is the only other time I've seen this issue.

Please let me know if that work :)

**Comment by lp20010415** [comment]
this?
![image](https://user-images.githubusercontent.com/56969920/129565789-2d4c1cc1-e085-49a8-8a68-f03036465ed4.png)

**Comment by lp20010415** [comment]
According to my research on the code, I think the problem lies in "subprocess. Open()"
look this
![image](https://user-images.githubusercontent.com/56969920/129566439-861bde13-9f5e-467a-ae92-70239ed7b2c5.png)
![image](https://user-images.githubusercontent.com/56969920/129566511-1a1d6da9-1e56-4ab9-931a-8f23c073dbe1.png)

**Comment by lp20010415** [comment]
然后，新建一个py文件，且模仿一个"subprocess.Popen()"，结果如下( 和上面一模一样)，所以我觉得问题出在"subprocess"
Translate:
As like as two peas, then create a new py file and imitate a "subprocess.Popen ()". The result is as follows (so the same as above), so I think the problem is "subprocess".
![image](https://user-images.githubusercontent.com/56969920/129567170-325b421e-6645-49e0-891e-8b52d67c38d5.png)

**Comment by NicklasTegner** [comment]
Hi
[WinError 5] indicates a permissions error.
So either:

* You do not have permission to execute pandoc in that folder.
* Pandoc itself is not executable

**Comment by lp20010415** [comment]
> Hi
> [WinError 5] indicates a permissions error.
> So either:
> 
> * You do not have permission to execute pandoc in that folder.
> * Pandoc itself is not executable

那我应该怎么给予权限呢？或者说怎么判断它是否是可执行文件呢？
Translate:
How should I give permission? Or how to judge whether it is an executable file?

**Comment by NicklasTegner** [comment]
Hi. This is beyond the scope of pypandoc and specific to your setup.
If you find a reproducible bug, feel free to reopen.

**Comment by lp20010415** [comment]
> Hi. This is beyond the scope of pypandoc and specific to your setup. If you find a reproducible bug, feel free to reopen.

Sorry, I remeber I say solved it, but i don't my reply is gone
