### ISSUE TITLE
Backslash appears when converting <br> tag to markdown

### ISSUE THREAD

**Issue by FrancisVila** [NicklasTegner/pypandoc#230]
When converting from html to markdown, a &lt;br&gt; tag adds a backslash to the output. 
```
ret = pypandoc.convert_text('<p>aaa <br> bbb </p>', 'md', format='html')
print(ret)
print(ret)
```

looks like this:
```
PS C:\projects\ST_docs_as_code\conversion_scripts> python .\test_li_list_detail.py
aaa\
bbb

aaa\
bbb
```
(I also tried with &lt;br/&gt;, &lt;br&gt;&lt;/br&gt;)

**Comment by NicklasTegner** [comment]
hi @FrancisVila 

this is actually the correct behaviour and not something that pypandoc does.
To see how to change this behaviour check the [Pandoc User Guide](https://pandoc.org/MANUAL.html)
