### ISSUE TITLE
Python 3.10 not mentioned as supported

### ISSUE THREAD

**Issue by h5rdly** [NicklasTegner/pypandoc#231]
Hi,

Not really an issue, buta small quirk - the main/README page only shows python 2.7-3.8 as supported.  
I was going to ask about Python 3.10 support/wheels, then decided to try pip first..

Could you perhaps update the readme to avoid confusion?

Thanks,
Eli

**Comment by NicklasTegner** [comment]
hi @h5rdly 
can you verify that PyPandoc works on Python 3.9 - 3.10?
