### ISSUE TITLE
how to add pandoc extension

### ISSUE THREAD

**Issue by lh6210** [NicklasTegner/pypandoc#234]
Hi there,
Could I know whether there's a way to include some extensions in the configuration of pypandoc, please?

There are several pandoc extensions that I want to install, but I didn't find the description in pypandoc's instructions.
Here's the pandoc's extension pages ---    https://pandoc.org/MANUAL.html#extensions

Thanks a lot.

**Comment by NicklasTegner** [comment]
hi there.

In pypandoc, you put all the extensions that you can enable or disable (with a - and +) after the to and from format.

so markdown+extension1-extension2 and so on.

Hope that helped, if not let me know :)

**Comment by lh6210** [comment]
That helps. Thanks!
