### ISSUE TITLE
Set cwd for pandoc process

### ISSUE THREAD

**Issue by mcm** [NicklasTegner/pypandoc#251]
I'm building an API based around pypandoc and would like to have pandoc executing with the working directory set to a one-time-use temp directory. Is there a currently supported way to do that? From what I can tell the answer is no, and if that's the case, would you be open to a PR adding a way to do so?

**Comment by NicklasTegner** [comment]
I would be open for a pr with this, with an optional cworkdir flag.
But wouldn't it just be easier to do:

```
old_wd = os.getcwd()
os.chdir("path/to/new/working/dir")
# execute pypandoc commands.
# restore old working dir
os.chdir(old_wd)
```

**Comment by mcm** [comment]
I did think of that, however the API could be handling multiple conversions at any given time, and the os.chdir would negatively affect other parallel requests. I think it would be smoothest for a cworkdir flag to be passed into the cwd argument in Popen when pandoc is called.

I'll work up a PR for this for your review

**Comment by mcm** [comment]
@NicklasTegner PR submitted. It's pretty straightforward, and the default behavior is unchanged by using `None` as the default.

Let me know if anything needs done differently.
