### ISSUE TITLE
Releases not shown on github

### ISSUE THREAD

**Issue by h5rdly** [NicklasTegner/pypandoc#266]
Hi,

I'm excited to see that pypandoc gets updated. 

However, the latest release shown here on github is `1.7.0` from Dec 2021, and I can't see what's new in the actual latest release (1.7.5).

Would it be possible to update the releases page?
https://github.com/NicklasTegner/pypandoc/releases

Thanks,
Eli

**Comment by NicklasTegner** [comment]
hi @h5rdly 

You can find the missing patches, here:

https://github.com/NicklasTegner/pypandoc/tags
