### ISSUE TITLE
Unnecessary files included with pip install

### ISSUE THREAD

**Issue by chris-mcdo** [NicklasTegner/pypandoc#270]
**Versions:** Ubuntu 20.04, python 3.9, pypandoc 1.7.5

Using `pip install pypandoc` creates the following files in my site-packages directory:

```
    site-packages/LICENSE
    site-packages/README.md
    site-packages/examples/services.py
    site-packages/filter_test.md
    site-packages/pypandoc/files/COPYRIGHT.txt
    site-packages/pypandoc/files/pandoc.exe
    site-packages/pypandoc-1.7.5.dist-info/*
    site-packages/pypandoc/*
    site-packages/tests.py
```

In other words, quite a few files are outside the package directories (`pypandoc/*` and `pypandoc-*.dist-info`).

This creates a few problems:

* The `examples/` directory looks like an installed package.
* The `tests.py` file in `site-packages` broke my `pytest` tests (due to some sort of name collision). This took a while to debug, since I don't expect installing packages to interfere with tests. 
* The `LICENCE` and `README` are confusing (which package do they belong to?) and are already present in the `pypandoc-1.7.5.dist-info` directory.

**First**, it seems preferable to keep all package files in the `pypandoc/*` and `pypandoc-*.dist-info` directories (unless absolutely necessary).

**Second**, the file `pypandoc/files/pandoc.exe` is useless to me (on linux), and is very(!) large (112MB). Maybe it could be made optional?

Thanks for reading! Please let me know what you think.

**Comment by NicklasTegner** [comment]
Hi.
Thanks for reporting this.
I was aware of the pandoc executable that had sneaked it's way into a binary dist of pypandoc.
However, I don't know what's causing the other files to be put there.
I'll investigate, and get back to you.

**Comment by NicklasTegner** [comment]
Hi again.
In future versions the test, readme and examples will no longer be included in the pip installables
