### ISSUE TITLE
No attribute 'convert_file'

### ISSUE THREAD

**Issue by asor12** [NicklasTegner/pypandoc#273]
Hi, I installed pypandoc for the first time and am getting this error: 

   output = pypandoc.convert_file('file.docx', 'plain', outputfile="file.txt")
AttributeError: module 'pypandoc' has no attribute 'convert_file'

I'm not sure why it wouldn't have that attribute?

**Comment by NicklasTegner** [comment]
Hi.

Without further information, I'm unable to reproduce this.

If you have more information. Feel free to provide them.
